version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/above-framework
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - run: npm run lint
      - run: npm run build

  publish:
    docker:
      - image: circleci/node:latest
    working_directory: ~/above-framework
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
      - build
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - build
